-- CREAR TABLESPACES
-- CREAR TABLESPACE PARA LAS TABLAS
CREATE TABLESPACE TS_TABLE_G 
  DATAFILE 'TS_TABLE_G.dbf'
  SIZE 1G
  AUTOEXTEND ON NEXT 200M
  MAXSIZE 3G;
  
-- CREAR TABLESPACE PARA LOS INDICES
CREATE TABLESPACE TS_INDEX_M
  DATAFILE 'TS_INDEX_M.dbf'
  SIZE 500M
  AUTOEXTEND ON NEXT 100M
  MAXSIZE 1G;

--------------------------------------------------
-- CREAR TABLAS
CREATE TABLE DB_RENTICAR.REN_CARACTERISTICAS(
    ID_CARACTERISTICAS NUMBER(6) NOT NULL,
    NOMBRE VARCHAR2(30) NOT NULL,
    EST_CARACTERISTICA VARCHAR2(20) NOT NULL,
    USR_CREACION VARCHAR2(20),
    FEC_CREACION DATE,
    USR_MODIFICACION VARCHAR2(20),
    FEC_MODIFICACION DATE
) TABLESPACE TS_TABLE_G;

CREATE TABLE DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS(
    ID_OPCIONES_CARACTERISTICAS NUMBER(6) NOT NULL,
    OPCION VARCHAR2(30) NOT NULL,
    PRECIO NUMBER(15) NOT NULL,
    ID_CARACTERISTICAS NUMBER(6),
    EST_OPCION_CARACTERISTICA VARCHAR2(20) NOT NULL,
    USR_CREACION VARCHAR2(20),
    FEC_CREACION DATE,
    USR_MODIFICACION VARCHAR2(20),
    FEC_MODIFICACION DATE
) TABLESPACE TS_TABLE_G;

CREATE TABLE DB_RENTICAR.REN_VEHICULOS(
    ID_VEHICULOS NUMBER(6) NOT NULL,
    PLACA VARCHAR2(10) NOT NULL,
    MARCA VARCHAR2(30) NOT NULL,
    MODELO VARCHAR2(30) NOT NULL,
    ANO NUMBER(5) NOT NULL,
    COLOR VARCHAR2(20) NOT NULL,
    PROPIO NUMBER(1) NOT NULL,
    EST_VEHICULO VARCHAR2(20) NOT NULL,
    USR_CREACION VARCHAR2(20),
    FEC_CREACION DATE,
    USR_MODIFICACION VARCHAR2(20),
    FEC_MODIFICACION DATE
) TABLESPACE TS_TABLE_G;

CREATE TABLE DB_RENTICAR.REN_CARACTERISTICAS_VEHICULOS(
    ID_CARACTERISTICAS_VEHICULOS NUMBER(6) NOT NULL,
    ID_VEHICULOS NUMBER(6),
    ID_OPCIONES_CARACTERISTICAS NUMBER(6),
    EST_CARACTERISTICA_VEHICULO VARCHAR2(20) NOT NULL,
    USR_CREACION VARCHAR2(20),
    FEC_CREACION DATE,
    USR_MODIFICACION VARCHAR2(20),
    FEC_MODIFICACION DATE
) TABLESPACE TS_TABLE_G;

CREATE TABLE DB_RENTICAR.REN_OCUPACIONES(
    ID_OCUPACIONES NUMBER(6) NOT NULL,
    FEC_OCUPACION DATE NOT NULL,
    OCUPACION_DUENO NUMBER(1) NOT NULL,
    ID_VEHICULOS NUMBER(6),
    EST_OCUPACION VARCHAR2(20) NOT NULL,
    USR_CREACION VARCHAR2(20),
    FEC_CREACION DATE,
    USR_MODIFICACION VARCHAR2(20),
    FEC_MODIFICACION DATE
)PARTITION BY RANGE (FEC_OCUPACION)( 
    PARTITION OCUPAC_2018 VALUES LESS THAN (TO_DATE('01-01-2018','DD-MM-YYYY')),
    PARTITION OCUPAC_2019 VALUES LESS THAN (TO_DATE('01-01-2019','DD-MM-YYYY')),
    PARTITION OCUPAC_2020 VALUES LESS THAN (TO_DATE('01-01-2020','DD-MM-YYYY')),
    PARTITION OCUPAC_2021 VALUES LESS THAN (TO_DATE('01-01-2021','DD-MM-YYYY')),
    PARTITION OCUPAC_2022 VALUES LESS THAN (TO_DATE('01-01-2022','DD-MM-YYYY')),
    PARTITION OCUPAC_2023 VALUES LESS THAN (TO_DATE('01-01-2023','DD-MM-YYYY')),
    PARTITION OCUPAC_2024 VALUES LESS THAN (TO_DATE('01-01-2024','DD-MM-YYYY')),
    PARTITION OCUPAC_MAX VALUES LESS THAN (MAXVALUE)
) TABLESPACE TS_TABLE_G;

CREATE TABLE DB_RENTICAR.REN_TIPOS_DOCUMENTOS(
    ID_TIPOS_DOCUMENTOS NUMBER(6) NOT NULL,
    DES_TIPO_DOCUMENTO VARCHAR2(20) NOT NULL,
    COD_TIPO_DOCUMENTO VARCHAR2(2) NOT NULL,
    EST_TIPO_DOCUMENTO VARCHAR2(20) NOT NULL,
    USR_CREACION VARCHAR2(20),
    FEC_CREACION DATE,
    USR_MODIFICACION VARCHAR2(20),
    FEC_MODIFICACION DATE
) TABLESPACE TS_TABLE_G;

CREATE TABLE DB_RENTICAR.REN_CLIENTES(
    ID_CLIENTES NUMBER(6) NOT NULL,
    NOMBRE VARCHAR2(30) NOT NULL,
    APELLIDO VARCHAR2(30) NOT NULL,
    TELEFONO VARCHAR2(20) NOT NULL,
    DIRECCION VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    NUM_DOCUMENTO NUMBER(15) NOT NULL,
    ID_TIPOS_DOCUMENTOS NUMBER(6) NOT NULL,
    EST_CLIENTE VARCHAR2(20) NOT NULL,
    USR_CREACION VARCHAR2(20),
    FEC_CREACION DATE,
    USR_MODIFICACION VARCHAR2(20),
    FEC_MODIFICACION DATE
) TABLESPACE TS_TABLE_G;

CREATE TABLE DB_RENTICAR.REN_ALQUILERES(
    ID_ALQUILERES NUMBER(6) NOT NULL,
    FEC_INICIO DATE NOT NULL,
    FEC_FIN DATE NOT NULL,
    TARIFA NUMBER(15) NOT NULL,
    ID_VEHICULOS NUMBER(6),
    ID_CLIENTES NUMBER(6),
    EST_ALQUILER VARCHAR2(20) NOT NULL,
    USR_CREACION VARCHAR2(20),
    FEC_CREACION DATE,
    USR_MODIFICACION VARCHAR2(20),
    FEC_MODIFICACION DATE
) TABLESPACE TS_TABLE_G;

CREATE TABLE DB_RENTICAR.REN_RECIBIDOS(
    ID_RECIBIDOS NUMBER(6) NOT NULL,
    NOVEDADES VARCHAR2(200) NOT NULL,
    SATISFACCION_SERVICIO NUMBER(2) NOT NULL,
    FEC_RECIBIDO DATE NOT NULL,
    ID_ALQUILERES NUMBER(6) NOT NULL,
    INGRESOS NUMBER(15) NOT NULL,
    EST_RECIBIDO VARCHAR2(20) NOT NULL,
    USR_CREACION VARCHAR2(20),
    FEC_CREACION DATE,
    USR_MODIFICACION VARCHAR2(20),
    FEC_MODIFICACION DATE
)PARTITION BY RANGE (FEC_RECIBIDO)( 
    PARTITION RECIBI_2018 VALUES LESS THAN (TO_DATE('01-01-2018','DD-MM-YYYY')),
    PARTITION RECIBI_2019 VALUES LESS THAN (TO_DATE('01-01-2019','DD-MM-YYYY')),
    PARTITION RECIBI_2020 VALUES LESS THAN (TO_DATE('01-01-2020','DD-MM-YYYY')),
    PARTITION RECIBI_2021 VALUES LESS THAN (TO_DATE('01-01-2021','DD-MM-YYYY')),
    PARTITION RECIBI_2022 VALUES LESS THAN (TO_DATE('01-01-2022','DD-MM-YYYY')),
    PARTITION RECIBI_2023 VALUES LESS THAN (TO_DATE('01-01-2023','DD-MM-YYYY')),
    PARTITION RECIBI_2024 VALUES LESS THAN (TO_DATE('01-01-2024','DD-MM-YYYY')),
    PARTITION RECIBI_MAX VALUES LESS THAN (MAXVALUE)
) TABLESPACE TS_TABLE_G;

CREATE TABLE DB_RENTICAR.REN_GASTOS(
    ID_GASTOS NUMBER(6) NOT NULL,
    TIPO_GASTO VARCHAR2(20) NOT NULL,
    COSTO NUMBER(15) NOT NULL,
    FEC_GASTO DATE NOT NULL,
    ID_VEHICULOS NUMBER(6) NOT NULL,
    EST_GASTO VARCHAR2(20) NOT NULL,
    USR_CREACION VARCHAR2(20),
    FEC_CREACION DATE,
    USR_MODIFICACION VARCHAR2(20),
    FEC_MODIFICACION DATE
)PARTITION BY RANGE (FEC_GASTO)( 
    PARTITION GASTOS_2018 VALUES LESS THAN (TO_DATE('01-01-2018','DD-MM-YYYY')),
    PARTITION GASTOS_2019 VALUES LESS THAN (TO_DATE('01-01-2019','DD-MM-YYYY')),
    PARTITION GASTOS_2020 VALUES LESS THAN (TO_DATE('01-01-2020','DD-MM-YYYY')),
    PARTITION GASTOS_2021 VALUES LESS THAN (TO_DATE('01-01-2021','DD-MM-YYYY')),
    PARTITION GASTOS_2022 VALUES LESS THAN (TO_DATE('01-01-2022','DD-MM-YYYY')),
    PARTITION GASTOS_2023 VALUES LESS THAN (TO_DATE('01-01-2023','DD-MM-YYYY')),
    PARTITION GASTOS_2024 VALUES LESS THAN (TO_DATE('01-01-2024','DD-MM-YYYY')),
    PARTITION GASTOS_MAX VALUES LESS THAN (MAXVALUE)
) TABLESPACE TS_TABLE_G;

-------------------------------------------------------
-- CREAR LLAVES PRIMARIAS
ALTER TABLE REN_CARACTERISTICAS ADD CONSTRAINT PK_CARACT PRIMARY KEY (ID_CARACTERISTICAS);
ALTER TABLE REN_OPCIONES_CARACTERISTICAS ADD CONSTRAINT PK_OPCION PRIMARY KEY (ID_OPCIONES_CARACTERISTICAS);
ALTER TABLE REN_VEHICULOS ADD CONSTRAINT PK_VEHICU PRIMARY KEY (ID_VEHICULOS);
ALTER TABLE REN_CARACTERISTICAS_VEHICULOS ADD CONSTRAINT PK_CARVEH PRIMARY KEY (ID_CARACTERISTICAS_VEHICULOS);
ALTER TABLE REN_OCUPACIONES ADD CONSTRAINT PK_OCUPAC PRIMARY KEY (ID_OCUPACIONES);
ALTER TABLE REN_TIPOS_DOCUMENTOS ADD CONSTRAINT PK_TIPOSD PRIMARY KEY (ID_TIPOS_DOCUMENTOS);
ALTER TABLE REN_CLIENTES ADD CONSTRAINT PK_CLIENT PRIMARY KEY (ID_CLIENTES);
ALTER TABLE REN_ALQUILERES ADD CONSTRAINT PK_ALQUIL PRIMARY KEY (ID_ALQUILERES);
ALTER TABLE REN_RECIBIDOS ADD CONSTRAINT PK_RECIBI PRIMARY KEY (ID_RECIBIDOS);
ALTER TABLE REN_GASTOS ADD CONSTRAINT PK_GASTOS PRIMARY KEY (ID_GASTOS);

-------------------------------------------------------
-- CREAR INDICES 
CREATE INDEX IDX_CARACT_01 ON REN_CARACTERISTICAS(NOMBRE) TABLESPACE TS_INDEX_M;
CREATE INDEX IDX_OPCION_01 ON REN_OPCIONES_CARACTERISTICAS(OPCION) TABLESPACE TS_INDEX_M;
CREATE INDEX IDX_VEHICU_01 ON REN_VEHICULOS(PLACA) TABLESPACE TS_INDEX_M;
CREATE INDEX IDX_OCUPAC_01 ON REN_OCUPACIONES(FEC_OCUPACION) TABLESPACE TS_INDEX_M;
CREATE INDEX IDX_OCUPAC_02 ON REN_OCUPACIONES(OCUPACION_DUENO) TABLESPACE TS_INDEX_M;
CREATE INDEX IDX_OCUPAC_03 ON REN_OCUPACIONES(ID_VEHICULOS) TABLESPACE TS_INDEX_M;
CREATE INDEX IDX_TIPOSD_01 ON REN_TIPOS_DOCUMENTOS(COD_TIPO_DOCUMENTO) TABLESPACE TS_INDEX_M;
CREATE INDEX IDX_CLIENT_01 ON REN_CLIENTES(NUM_DOCUMENTO, ID_TIPOS_DOCUMENTOS) TABLESPACE TS_INDEX_M;
CREATE INDEX IDX_RECIBI_01 ON REN_RECIBIDOS(FEC_RECIBIDO) TABLESPACE TS_INDEX_M;
CREATE INDEX IDX_GASTOS_01 ON REN_GASTOS(FEC_GASTO) TABLESPACE TS_INDEX_M;

-------------------------------------------------------
-- CREAR LLAVES FORANEAS
ALTER TABLE REN_OPCIONES_CARACTERISTICAS ADD CONSTRAINT FK_OPCION_CARACT_01 FOREIGN KEY(ID_CARACTERISTICAS) 
    REFERENCES REN_CARACTERISTICAS(ID_CARACTERISTICAS);
    
ALTER TABLE REN_CARACTERISTICAS_VEHICULOS ADD CONSTRAINT FK_CARVEH_VEHICU_01 FOREIGN KEY(ID_VEHICULOS) 
    REFERENCES REN_VEHICULOS(ID_VEHICULOS);

ALTER TABLE REN_CARACTERISTICAS_VEHICULOS ADD CONSTRAINT FK_CARVEH_OPCION_02 FOREIGN KEY(ID_OPCIONES_CARACTERISTICAS) 
    REFERENCES REN_OPCIONES_CARACTERISTICAS(ID_OPCIONES_CARACTERISTICAS);
    
ALTER TABLE REN_OCUPACIONES ADD CONSTRAINT FK_OCUPAC_VEHICU_01 FOREIGN KEY(ID_VEHICULOS) 
    REFERENCES REN_VEHICULOS(ID_VEHICULOS);
    
ALTER TABLE REN_CLIENTES ADD CONSTRAINT FK_CLIENT_TIPOSD_01 FOREIGN KEY(ID_TIPOS_DOCUMENTOS) 
    REFERENCES REN_TIPOS_DOCUMENTOS(ID_TIPOS_DOCUMENTOS);
 
ALTER TABLE REN_ALQUILERES ADD CONSTRAINT FK_ALQUIL_VEHICU_01 FOREIGN KEY(ID_VEHICULOS) 
    REFERENCES REN_VEHICULOS(ID_VEHICULOS);   

ALTER TABLE REN_ALQUILERES ADD CONSTRAINT FK_ALQUIL_CLIENT_02 FOREIGN KEY(ID_CLIENTES) 
    REFERENCES REN_CLIENTES(ID_CLIENTES);

ALTER TABLE REN_RECIBIDOS ADD CONSTRAINT FK_RECIBI_ALQUIL_01 FOREIGN KEY(ID_ALQUILERES) 
    REFERENCES REN_ALQUILERES(ID_ALQUILERES);

ALTER TABLE REN_GASTOS ADD CONSTRAINT FK_GASTOS_VEHICU_01 FOREIGN KEY(ID_VEHICULOS) 
    REFERENCES REN_VEHICULOS(ID_VEHICULOS);
    
-------------------------------------------------------
-- CREAR LLAVES UNICAS
ALTER TABLE REN_CARACTERISTICAS ADD CONSTRAINT UK_CARACT_01 UNIQUE(NOMBRE);
ALTER TABLE REN_OPCIONES_CARACTERISTICAS ADD CONSTRAINT UK_OPCION_01 UNIQUE(OPCION, ID_CARACTERISTICAS);
ALTER TABLE REN_VEHICULOS ADD CONSTRAINT UK_VEHICU_01 UNIQUE(PLACA);
ALTER TABLE REN_TIPOS_DOCUMENTOS ADD CONSTRAINT UK_TIPOSD_01 UNIQUE(COD_TIPO_DOCUMENTO);
ALTER TABLE REN_CLIENTES ADD CONSTRAINT UK_CLIENT_01 UNIQUE(NUM_DOCUMENTO, ID_TIPOS_DOCUMENTOS);

-------------------------------------------------------
-- CREAR SECUENCIAS
CREATE SEQUENCE DB_RENTICAR.SEQ_ID_CARACTERISTICAS MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 10 NOCYCLE;

CREATE SEQUENCE DB_RENTICAR.SEQ_ID_OPCIONES MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 20 NOCYCLE;

CREATE SEQUENCE DB_RENTICAR.SEQ_ID_VEHICULOS MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCYCLE;

CREATE SEQUENCE DB_RENTICAR.SEQ_ID_CARACTERISTICAS_VEHICULOS MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCYCLE;

CREATE SEQUENCE DB_RENTICAR.SEQ_ID_OCUPACIONES MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCYCLE;

CREATE SEQUENCE DB_RENTICAR.SEQ_ID_TIPOS_DOCUMENTOS MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCYCLE;

CREATE SEQUENCE DB_RENTICAR.SEQ_ID_CLIENTES MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCYCLE;

CREATE SEQUENCE DB_RENTICAR.SEQ_ID_ALQUILERES MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCYCLE;

CREATE SEQUENCE DB_RENTICAR.SEQ_ID_RECIBIDOS MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCYCLE;

CREATE SEQUENCE DB_RENTICAR.SEQ_ID_GASTOS MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCYCLE;

-------------------------------------------------------
-- CREAR TRIGGERS
-- TRIGGER PARA INSERTAR EL ID DE LA TABLA REN_CARACTERISTICAS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BIR_CARACT
    BEFORE INSERT ON REN_CARACTERISTICAS FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ID_CARACTERISTICAS IS NULL THEN 
            SELECT SEQ_ID_CARACTERISTICAS.NEXTVAL INTO :NEW.ID_CARACTERISTICAS FROM DUAL;
            
        END IF; 
        SELECT SYSDATE INTO :NEW.FEC_CREACION FROM DUAL;
    END IF; 
END;
/

-- TRIGGER PARA INSERTAR EL ID DE LA TABLA REN_OPCIONES_CARACTERISTICAS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BIR_OPCION
    BEFORE INSERT ON REN_OPCIONES_CARACTERISTICAS FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ID_OPCIONES_CARACTERISTICAS IS NULL THEN 
            SELECT SEQ_ID_OPCIONES.NEXTVAL INTO :NEW.ID_OPCIONES_CARACTERISTICAS FROM DUAL;
            
        END IF; 
        SELECT SYSDATE INTO :NEW.FEC_CREACION FROM DUAL;
    END IF; 
END;
/

-- TRIGGER PARA INSERTAR EL ID DE LA TABLA REN_VEHICULOS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BIR_VEHICU
    BEFORE INSERT ON REN_VEHICULOS FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ID_VEHICULOS IS NULL THEN 
            SELECT SEQ_ID_VEHICULOS.NEXTVAL INTO :NEW.ID_VEHICULOS FROM DUAL;
            
        END IF; 
        SELECT SYSDATE INTO :NEW.FEC_CREACION FROM DUAL;
    END IF; 
END;
/

-- TRIGGER PARA INSERTAR EL ID DE LA TABLA REN_CARACTERISTICAS_VEHICULOS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BIR_CARVEH
    BEFORE INSERT ON REN_CARACTERISTICAS_VEHICULOS FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ID_CARACTERISTICAS_VEHICULOS IS NULL THEN 
            SELECT SEQ_ID_CARACTERISTICAS_VEHICULOS.NEXTVAL INTO :NEW.ID_CARACTERISTICAS_VEHICULOS FROM DUAL;
            
        END IF; 
        SELECT SYSDATE INTO :NEW.FEC_CREACION FROM DUAL;
    END IF; 
END;
/

-- TRIGGER PARA INSERTAR EL ID DE LA TABLA REN_OCUPACIONES
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BIR_OCUPAC
    BEFORE INSERT ON REN_OCUPACIONES FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ID_OCUPACIONES IS NULL THEN 
            SELECT SEQ_ID_OCUPACIONES.NEXTVAL INTO :NEW.ID_OCUPACIONES FROM DUAL;
            
        END IF; 
        SELECT SYSDATE INTO :NEW.FEC_CREACION FROM DUAL;
    END IF; 
END;
/

-- TRIGGER PARA INSERTAR EL ID DE LA TABLA REN_TIPOS_DOCUMENTOS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BIR_TIPOSD
    BEFORE INSERT ON REN_TIPOS_DOCUMENTOS FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ID_TIPOS_DOCUMENTOS IS NULL THEN 
            SELECT SEQ_ID_TIPOS_DOCUMENTOS.NEXTVAL INTO :NEW.ID_TIPOS_DOCUMENTOS FROM DUAL;
            
        END IF; 
        SELECT SYSDATE INTO :NEW.FEC_CREACION FROM DUAL;
    END IF; 
END;
/

-- TRIGGER PARA INSERTAR EL ID DE LA TABLA REN_CLIENTES
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BIR_CLIENT
    BEFORE INSERT ON REN_CLIENTES FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ID_CLIENTES IS NULL THEN 
            SELECT SEQ_ID_CLIENTES.NEXTVAL INTO :NEW.ID_CLIENTES FROM DUAL;
            
        END IF; 
        SELECT SYSDATE INTO :NEW.FEC_CREACION FROM DUAL;
    END IF; 
END;
/

-- TRIGGER PARA INSERTAR EL ID DE LA TABLA REN_ALQUILERES
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BIR_ALQUIL
    BEFORE INSERT ON REN_ALQUILERES FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ID_ALQUILERES IS NULL THEN 
            SELECT SEQ_ID_ALQUILERES.NEXTVAL INTO :NEW.ID_ALQUILERES FROM DUAL;
            
        END IF; 
        SELECT SYSDATE INTO :NEW.FEC_CREACION FROM DUAL;
    END IF; 
END;
/

-- TRIGGER PARA INSERTAR EL ID DE LA TABLA REN_RECIBIDOS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BIR_RECIBI
    BEFORE INSERT ON REN_RECIBIDOS FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ID_RECIBIDOS IS NULL THEN 
            SELECT SEQ_ID_RECIBIDOS.NEXTVAL INTO :NEW.ID_RECIBIDOS FROM DUAL;
            
        END IF; 
        SELECT SYSDATE INTO :NEW.FEC_CREACION FROM DUAL;
    END IF; 
END;
/

-- TRIGGER PARA INSERTAR EL ID DE LA TABLA REN_GASTOS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BIR_GASTOS
    BEFORE INSERT ON REN_GASTOS FOR EACH ROW 
BEGIN  
    IF INSERTING THEN 
        IF :NEW.ID_GASTOS IS NULL THEN 
            SELECT SEQ_ID_GASTOS.NEXTVAL INTO :NEW.ID_GASTOS FROM DUAL;
            
        END IF; 
        SELECT SYSDATE INTO :NEW.FEC_CREACION FROM DUAL;
    END IF; 
END;
/

-------------------------------------------------------------------

-- TRIGGER PARA AUDITORIA DE LA TABLA REN_CARACTERISTICAS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BUR_CARACT
    BEFORE UPDATE ON REN_CARACTERISTICAS FOR EACH ROW 
BEGIN  
    IF UPDATING THEN 
        SELECT SYSDATE INTO :NEW.FEC_MODIFICACION FROM DUAL;
    END IF; 
END;
/

-- TRIGGER PARA AUDITORIA DE LA TABLA REN_OPCIONES_CARACTERISTICAS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BUR_OPCION
    BEFORE UPDATE ON REN_OPCIONES_CARACTERISTICAS FOR EACH ROW 
BEGIN  
    IF UPDATING THEN 
        SELECT SYSDATE INTO :NEW.FEC_MODIFICACION FROM DUAL;
    END IF;
END;
/

-- TRIGGER PARA AUDITORIA DE LA TABLA REN_VEHICULOS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BUR_VEHICU
    BEFORE UPDATE ON REN_VEHICULOS FOR EACH ROW 
BEGIN  
    IF UPDATING THEN 
        SELECT SYSDATE INTO :NEW.FEC_MODIFICACION FROM DUAL;
    END IF;
END;
/

-- TRIGGER PARA AUDITORIA DE LA TABLA REN_CARACTERISTICAS_VEHICULOS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BUR_CARVEH
    BEFORE UPDATE ON REN_CARACTERISTICAS_VEHICULOS FOR EACH ROW 
BEGIN  
    IF UPDATING THEN 
        SELECT SYSDATE INTO :NEW.FEC_MODIFICACION FROM DUAL;
    END IF;
END;
/

-- TRIGGER PARA AUDITORIA DE LA TABLA REN_OCUPACIONES
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BUR_OCUPAC
    BEFORE UPDATE ON REN_OCUPACIONES FOR EACH ROW 
BEGIN  
    IF UPDATING THEN 
        SELECT SYSDATE INTO :NEW.FEC_MODIFICACION FROM DUAL;
    END IF;
END;
/

-- TRIGGER PARA AUDITORIA DE LA TABLA REN_TIPOS_DOCUMENTOS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BUR_TIPOSD
    BEFORE UPDATE ON REN_TIPOS_DOCUMENTOS FOR EACH ROW 
BEGIN  
    IF UPDATING THEN 
        SELECT SYSDATE INTO :NEW.FEC_MODIFICACION FROM DUAL;
    END IF;
END;
/

-- TRIGGER PARA AUDITORIA DE LA TABLA REN_CLIENTES
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BUR_CLIENT
    BEFORE UPDATE ON REN_CLIENTES FOR EACH ROW 
BEGIN  
    IF UPDATING THEN 
        SELECT SYSDATE INTO :NEW.FEC_MODIFICACION FROM DUAL;
    END IF;
END;
/

-- TRIGGER PARA AUDITORIA DE LA TABLA REN_ALQUILERES
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BUR_ALQUIL
    BEFORE UPDATE ON REN_ALQUILERES FOR EACH ROW 
BEGIN  
    IF UPDATING THEN 
        SELECT SYSDATE INTO :NEW.FEC_MODIFICACION FROM DUAL;
    END IF;
END;
/

-- TRIGGER PARA AUDITORIA DE LA TABLA REN_RECIBIDOS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BUR_RECIBI
    BEFORE UPDATE ON REN_RECIBIDOS FOR EACH ROW 
BEGIN  
    IF UPDATING THEN 
        SELECT SYSDATE INTO :NEW.FEC_MODIFICACION FROM DUAL;
    END IF;
END;
/

-- TRIGGER PARA AUDITORIA DE LA TABLA REN_GASTOS
CREATE OR REPLACE EDITIONABLE TRIGGER TR_BUR_GASTOS
    BEFORE UPDATE ON REN_GASTOS FOR EACH ROW 
BEGIN  
    IF UPDATING THEN 
        SELECT SYSDATE INTO :NEW.FEC_MODIFICACION FROM DUAL;
    END IF;
END;
/

-------------------------------------------------------
-- CREAR PROCEDIMIENTOS
-- PROCEDIMIENTO PARA AUMENTAR EL PRECIO DE TODAS LAS OPCIONES DE FORMA MASIVA
CREATE OR REPLACE PROCEDURE aumentarPrecioCaracteristicas(l_porcentaje IN NUMBER)
AS
    c_aumento NUMBER(5,2):= l_porcentaje/100;
BEGIN
    UPDATE REN_OPCIONES_CARACTERISTICAS SET PRECIO = CEIL(PRECIO * c_aumento + PRECIO);
END;
/

------------------------------------------------------
-- CREAR FUNCIONES
-- FUNCION PARA TRAER LOS GASTOS E INGRESOS DE TODOS LOS VEHICULOS EN UN AÑO
CREATE OR REPLACE FUNCTION reporteGastos(l_ano IN VARCHAR2)RETURN SYS_REFCURSOR 
IS 
c_reporte SYS_REFCURSOR;

BEGIN
    OPEN c_reporte FOR 
        SELECT vehicu.PLACA, vehicu.MARCA, vehicu.MODELO, vehicu.ANO, vehicu.COLOR, vehicu.PROPIO, 
            NVL((SELECT  /*+ INDEX(REN_GASTOS IDX_GASTOS_01) */  SUM(gastos.COSTO)
                FROM REN_GASTOS gastos 
                WHERE vehicu.ID_VEHICULOS = gastos.ID_VEHICULOS
                AND TO_CHAR(gastos.FEC_GASTO,'YYYY') = l_ano),0)  AS GASTOS,
            NVL((SELECT /*+ INDEX(REN_RECIBIDOS IDX_RECIBI_01) */ SUM(recibi.INGRESOS)
                FROM REN_ALQUILERES alquil
                JOIN REN_RECIBIDOS recibi
                ON vehicu.ID_VEHICULOS = alquil.ID_VEHICULOS
                AND  alquil.ID_ALQUILERES = recibi.ID_ALQUILERES
                AND TO_CHAR(recibi.FEC_RECIBIDO,'YYYY') = l_ano),0) AS INGRESOS
FROM REN_VEHICULOS vehicu
WHERE EST_VEHICULO = 'ACTIVO';
    RETURN c_reporte;
    CLOSE c_reporte;
END reporteGastos;
/

-- FUNCION PARA TRAER LOS REPORTES DE ALQUILADOS DE TODOS LOS VEHICULOS CONS NOVEDADES Y SATISFACCION POR AÑO Y MES
CREATE OR REPLACE FUNCTION reporteAlquileres(l_fecha IN VARCHAR2)RETURN SYS_REFCURSOR 
IS 
c_reporte SYS_REFCURSOR;
BEGIN
    OPEN c_reporte FOR 
    SELECT vehicu.PLACA, vehicu.MARCA, vehicu.MODELO, vehicu.ANO, vehicu.COLOR, vehicu.PROPIO,
    NVL((SELECT /*+ INDEX(REN_GASTOS IDX_GASTOS_01) */ SUM(gastos.COSTO)
        FROM REN_GASTOS gastos 
            WHERE vehicu.ID_VEHICULOS = gastos.ID_VEHICULOS
            AND TO_CHAR(gastos.FEC_GASTO,'MM-YYYY') = l_fecha ),0) AS GASTOS,
    NVL((SELECT /*+ INDEX(REN_RECIBIDOS IDX_RECIBI_01) */ SUM(recibi.INGRESOS)
        FROM REN_ALQUILERES alquil
            JOIN REN_RECIBIDOS recibi
            ON vehicu.ID_VEHICULOS = alquil.ID_VEHICULOS
            AND  alquil.ID_ALQUILERES = recibi.ID_ALQUILERES
            AND TO_CHAR(recibi.FEC_RECIBIDO,'MM-YYYY') = l_fecha),0) AS INGRESOS,
    (SELECT /*+ INDEX_JOIN(REN_OCUPACIONES IDX_OCUPAC_01 IDX_OCUPAC_02) */ COUNT(ocupac.ID_OCUPACIONES) FROM REN_OCUPACIONES ocupac
        WHERE vehicu.ID_VEHICULOS = ocupac.ID_VEHICULOS
        AND TO_CHAR(ocupac.FEC_OCUPACION,'MM-YYYY') = l_fecha
        AND ocupac.OCUPACION_DUENO = 0) AS DIAS,
    NVL((SELECT AVG(recibi.SATISFACCION_SERVICIO)
        FROM REN_ALQUILERES alquil
        JOIN REN_RECIBIDOS recibi
            ON vehicu.ID_VEHICULOS = alquil.ID_VEHICULOS
            AND  alquil.ID_ALQUILERES = recibi.ID_ALQUILERES
            AND TO_CHAR(recibi.FEC_RECIBIDO,'MM-YYYY') = l_fecha),0) AS SATISFACCION,
    NVL((SELECT LISTAGG(recibi.NOVEDADES, ' - ')
        FROM REN_ALQUILERES alquil
        JOIN REN_RECIBIDOS recibi
            ON vehicu.ID_VEHICULOS = alquil.ID_VEHICULOS
            AND  alquil.ID_ALQUILERES = recibi.ID_ALQUILERES
            AND TO_CHAR(recibi.FEC_RECIBIDO,'MM-YYYY') = l_fecha),'-') AS NOVEDADES  
FROM REN_VEHICULOS vehicu
WHERE EST_VEHICULO = 'ACTIVO';
    RETURN c_reporte;
    CLOSE c_reporte;
END reporteAlquileres;
/

-- FUNCION PARA TRAER LOS GASTOS SUMADOS DE TODOS LOS VEHICULOS
CREATE OR REPLACE FUNCTION sumaGastosVehiculos(l_var IN NUMBER)RETURN SYS_REFCURSOR 
IS 
c_suma SYS_REFCURSOR;

BEGIN
    OPEN c_suma FOR 
        SELECT /*+ INDEX(REN_VEHICULOS IDX_VEHICU_01) */ vehicu.ID_VEHICULOS, vehicu.PLACA, vehicu.MARCA, vehicu.MODELO, vehicu.ANO, vehicu.COLOR, vehicu.PROPIO, 
            CASE  WHEN SUM(gasto.COSTO) > 0 THEN SUM(gasto.COSTO) ELSE 0 END AS GASTOS
        FROM REN_VEHICULOS vehicu
            LEFT OUTER JOIN REN_GASTOS gasto
                ON vehicu.ID_VEHICULOS = gasto.ID_VEHICULOS
        WHERE EST_VEHICULO = 'ACTIVO'
        GROUP BY vehicu.ID_VEHICULOS, vehicu.PLACA, vehicu.MARCA, vehicu.MODELO, vehicu.ANO, vehicu.COLOR, vehicu.PROPIO;
    RETURN c_suma;
    CLOSE c_suma;
END sumaGastosVehiculos;
/