-- INSERTAR DATOS
-- INSERTAR TIPOS DE DOCUMENTOS
INSERT ALL 
INTO DB_RENTICAR.REN_TIPOS_DOCUMENTOS (DES_TIPO_DOCUMENTO, COD_TIPO_DOCUMENTO, EST_TIPO_DOCUMENTO, USR_CREACION) 
    VALUES ('CEDULA CIUDADANIA', 'CC', 'ACTIVO', 'DB_RENTICAR') 
INTO DB_RENTICAR.REN_TIPOS_DOCUMENTOS (DES_TIPO_DOCUMENTO, COD_TIPO_DOCUMENTO, EST_TIPO_DOCUMENTO, USR_CREACION) 
    VALUES ('CEDULA EXTRANGERIA', 'CE', 'ACTIVO', 'DB_RENTICAR')
INTO DB_RENTICAR.REN_TIPOS_DOCUMENTOS (DES_TIPO_DOCUMENTO, COD_TIPO_DOCUMENTO, EST_TIPO_DOCUMENTO, USR_CREACION) 
    VALUES ('TARJETA IDENTIDAD', 'TI', 'ACTIVO', 'DB_RENTICAR')
SELECT * FROM DUAL;

-- INSERTAR CARACTERISTICAS
INSERT ALL 
INTO DB_RENTICAR.REN_CARACTERISTICAS (ID_CARACTERISTICAS, NOMBRE, EST_CARACTERISTICA, USR_CREACION) 
    VALUES (1, 'CONFORT', 'ACTIVO', 'DB_RENTICAR') 
INTO DB_RENTICAR.REN_CARACTERISTICAS (ID_CARACTERISTICAS, NOMBRE, EST_CARACTERISTICA, USR_CREACION) 
    VALUES (2, 'VELOCIDAD MAXIMA', 'ACTIVO', 'DB_RENTICAR')
INTO DB_RENTICAR.REN_CARACTERISTICAS (ID_CARACTERISTICAS, NOMBRE, EST_CARACTERISTICA, USR_CREACION) 
    VALUES (3, 'CAPACIDAD', 'ACTIVO', 'DB_RENTICAR') 
INTO DB_RENTICAR.REN_CARACTERISTICAS (ID_CARACTERISTICAS, NOMBRE, EST_CARACTERISTICA, USR_CREACION) 
    VALUES (4, 'ANTIGUEDAD', 'ACTIVO', 'DB_RENTICAR') 
SELECT * FROM DUAL;

-- INSERTAR OPCIONES
INSERT ALL 
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (1, 'BASICO', 1000, 1, 'ACTIVO', 'DB_RENTICAR') 
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (2, 'ESTANDAR', 2000, 1, 'ACTIVO', 'DB_RENTICAR') 
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (3, 'PREMIUM', 3000, 1, 'ACTIVO', 'DB_RENTICAR') 
    
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (4, '110', 1000, 2, 'ACTIVO', 'DB_RENTICAR') 
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (5, '120', 2000, 2, 'ACTIVO', 'DB_RENTICAR') 
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (6, '150', 3000, 2, 'ACTIVO', 'DB_RENTICAR') 
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (7, '+150', 5000, 2, 'ACTIVO', 'DB_RENTICAR') 

INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (8, '2', 500, 3, 'ACTIVO', 'DB_RENTICAR')
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (9, '3', 1500, 3, 'ACTIVO', 'DB_RENTICAR')
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (10, '5', 3000, 3, 'ACTIVO', 'DB_RENTICAR')
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (11, '7', 5000, 3, 'ACTIVO', 'DB_RENTICAR')
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (12, '+7', 7000, 3, 'ACTIVO', 'DB_RENTICAR')

INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (13, '1 AÑO', 6000, 4, 'ACTIVO', 'DB_RENTICAR')
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (14, '2 AÑOS', 5500, 4, 'ACTIVO', 'DB_RENTICAR')
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (15, '3 AÑOS', 4000, 4, 'ACTIVO', 'DB_RENTICAR')
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (16, '5 AÑOS', 2500, 4, 'ACTIVO', 'DB_RENTICAR')
INTO DB_RENTICAR.REN_OPCIONES_CARACTERISTICAS (ID_OPCIONES_CARACTERISTICAS, OPCION, PRECIO, ID_CARACTERISTICAS, EST_OPCION_CARACTERISTICA, USR_CREACION) 
    VALUES (17, '+5 AÑOS', 1000, 4, 'ACTIVO', 'DB_RENTICAR')
SELECT * FROM DUAL;
